name: mobile_test_demo
description: Mobile Test Demo using Clean Architecture + Bloc + Multi-Env
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # --- Routing ---
  go_router: ^14.1.0

  # --- State Management ---
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # --- Dependency Injection ---
  get_it: ^7.6.0

  # --- JSON + Helpers ---
  json_annotation: ^4.9.0

  # --- HTTP / Networking ---
  dio: ^5.4.0

  # --- ENV / Config ---
  flutter_dotenv: ^5.1.0 # optional if you later want .env files

  # --- Utilities ---
  logger: ^2.0.2
  intl: ^0.19.0
  fpdart: ^1.2.0
  formz: ^0.8.0
  provider: ^6.1.5+1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- Code Generation ---
  build_runner: ^2.4.6
  json_serializable: ^6.8.0

  # --- Testing Tools ---
  mocktail: ^1.0.2
  bloc_test: ^9.1.5

  # --- Linter ---
  flutter_lints: ^3.0.1
  # very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock_contacts.json
    - assets/images/
